### ISSUE TITLE
need node_turnkey_api.h

### ISSUE THREAD

**Issue by guozijijiu** [crolando/qt-imgui-nodes#1]
Hi, i didn't find node_turnkey_api.h/cpp files , could you please provide it  ?

#include <node_turnkey_api.h>

**Comment by crolando** [comment]
Sorry, I've been really messy with this.  I started adding too many features to this repo, and then eventually didn't want to support QT anymore.  So I gave up and left it in a broken state.  

But the problem is - I should have reverted the changes, so the value of this one is still there for people like you.

For now, please try to use really early versions of this repo like this one (jan 24, 2022).  This is before I went down the rabbit hole. 

https://github.com/crolando/qt-imgui-nodes/tree/91080a58babd4f23c14a0309d32fa3c869a0dd28

Can you confirm if that works? If it does, I will revert the changes.

The advanced functionality that I broke out is now in the nodos and plano projects.

**Comment by guozijijiu** [comment]
Thanks , let me try

**Comment by guozijijiu** [comment]
@crolando  , i have tryed it , seems still miss some files , can't find these API below
Application_Finalize(); 
Application_Initialize();  
Application_Frame();

**Comment by crolando** [comment]
Ah okay, I think I found it.  it requires an old version of imgui-node-editor as well.  thedmd changed his examples structure so that the example applications started inheriting methods from a base applcation class.  

this project depends on the examples from that project (which is not great because those have no guarantee to be stable).  

The easiest thing to do would be to downversion your copy of imgui-node-editor to this one:

https://github.com/thedmd/imgui-node-editor/commit/050b490b6506a52f377227d28acc834bc305d8c1

**Comment by crolando** [comment]
But generally speaking you may want to use this project as an example and roll your own that is structured in a way you like.  You may like to check out my plano library (which has a reference implementation in the nodos project).  This has some more features than the blueprint example, but nodos runs in SDL.  You could build a QT backend for plano using some of the cues from this project (namely using https://github.com/seanchas116/qtimgui).
